"""customers: who changed each consent flag, and when

PDPL asks a salon to be able to show that consent was given. The flags alone
could not: reception could opt a customer in to marketing and the record would
look the same as the customer doing it. `CustomerService.update_consent` now
fills these on every change, and refuses staff turning marketing on.

Rows that already had a flag on keep null provenance: their origin predates
this record and is unknown, which is the honest value.

Revision ID: 616b7a77b40b
Revises: f8a9b0c1d2e3
Create Date: 2026-09-23 20:10:05.075586

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "616b7a77b40b"
down_revision: str | Sequence[str] | None = "f8a9b0c1d2e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers", sa.Column("marketing_consent_source", sa.String(length=16), nullable=True)
    )
    op.add_column("customers", sa.Column("marketing_consent_by", sa.UUID(), nullable=True))
    op.add_column(
        "customers", sa.Column("marketing_consent_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "customers", sa.Column("whatsapp_consent_source", sa.String(length=16), nullable=True)
    )
    op.add_column("customers", sa.Column("whatsapp_consent_by", sa.UUID(), nullable=True))
    op.add_column(
        "customers", sa.Column("whatsapp_consent_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "whatsapp_consent_at")
    op.drop_column("customers", "whatsapp_consent_by")
    op.drop_column("customers", "whatsapp_consent_source")
    op.drop_column("customers", "marketing_consent_at")
    op.drop_column("customers", "marketing_consent_by")
    op.drop_column("customers", "marketing_consent_source")
    # ### end Alembic commands ###
