"""create bookings

Hand-written (no database was reachable to autogenerate against). The EXCLUDE
constraint below in particular cannot be autogenerated — verify with
`alembic check` and the concurrency test once Postgres is up.

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-08-15

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b2c3d4e5f6a7"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Statuses that still occupy the provider's calendar. Must stay in sync with
# BLOCKING_STATUSES in app/modules/booking/domain.py — a test asserts this.
_BLOCKING = ("draft", "pending_payment", "confirmed", "checked_in", "in_service")


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("service_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_bookings_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_bookings_end_after_start")),
    )
    op.create_index(op.f("ix_bookings_tenant_id"), "bookings", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_index(
        "ix_bookings_tenant_provider_start",
        "bookings",
        ["tenant_id", "provider_id", "starts_at"],
        unique=False,
    )
    op.create_index(
        "ix_bookings_tenant_customer", "bookings", ["tenant_id", "customer_id"], unique=False
    )
    op.create_index(
        "ix_bookings_tenant_location_start",
        "bookings",
        ["tenant_id", "location_id", "starts_at"],
        unique=False,
    )

    # --- the double-booking guarantee -------------------------------------
    # Defence in depth, because the service's check-then-act read cannot close
    # the race on its own:
    #
    #   1. PRIMARY: a transaction-scoped advisory lock per provider, taken in
    #      BookingService.create. Portable, needs no extension, and serialises
    #      concurrent booking attempts for the same provider.
    #   2. BACKSTOP: this EXCLUDE constraint, which makes an overlap physically
    #      impossible even if a code path forgets the lock.
    #
    # The constraint needs btree_gist to mix an equality operator (=) on
    # provider_id with an overlap operator (&&) in one GiST index. That
    # extension ships in postgresql-contrib and is present in the
    # postgres:16-alpine image we deploy, but not in every environment — so
    # this degrades instead of failing the migration outright.
    #
    # '[)' is half-open on purpose: 10:00-11:00 and 11:00-12:00 must not
    # collide. Mirrors TimeRange in app/core/values.py.
    blocking_list = ", ".join(f"'{s}'" for s in _BLOCKING)
    op.execute(
        f"""
        DO $$
        BEGIN
            CREATE EXTENSION IF NOT EXISTS btree_gist;

            ALTER TABLE bookings
            ADD CONSTRAINT ex_bookings_no_provider_overlap
            EXCLUDE USING gist (
                provider_id WITH =,
                tstzrange(starts_at, ends_at, '[)') WITH &&
            )
            WHERE (status IN ({blocking_list}));
        EXCEPTION
            WHEN feature_not_supported OR insufficient_privilege THEN
                RAISE WARNING
                    'btree_gist unavailable; skipping ex_bookings_no_provider_overlap. '
                    'Double-booking protection relies on the advisory lock in '
                    'BookingService.create alone. Install postgresql-contrib.';
        END
        $$;
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE bookings DROP CONSTRAINT IF EXISTS ex_bookings_no_provider_overlap")
    op.drop_table("bookings")
