"""subscription_checkouts: paying for a paid plan on Moyasar's hosted page

A Studio or Chain subscription now starts as `pending_payment` and is billed
and gated as Solo until its first payment is verified. Each attempt is a row
here, deliberately not in `payments`: those are a salon's takings, paid out to
it daily; this is what the salon pays NOVA. `covers_from`/`covers_until` stop
the monthly close charging the subscription again for months already paid.

Tenant-owned, so row-level security is enabled and forced here, which
autogenerate does not emit. `subscriptions.status` needs no change: it is a
non-native enum column with no check constraint.

Revision ID: f1b21a26382c
Revises: a9b0c1d2e3f4
Create Date: 2026-09-24 00:29:43.478894

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1b21a26382c"
down_revision: str | Sequence[str] | None = "a9b0c1d2e3f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TENANT = """
    current_setting('app.bypass_rls', true) = 'on'
    OR tenant_id::text = current_setting('app.current_tenant_id', true)
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_checkouts",
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("SOLO", "STUDIO", "CHAIN", name="plan_tier", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("annual", sa.Boolean(), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("covers_from", sa.Date(), nullable=False),
        sa.Column("covers_until", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PAID", "FAILED", name="checkout_status", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("gateway_invoice_id", sa.String(length=255), nullable=True),
        sa.Column("gateway_payment_id", sa.String(length=255), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "covers_until > covers_from", name=op.f("ck_subscription_checkouts_covers_forward")
        ),
        sa.CheckConstraint(
            "net_amount >= 0 AND vat_amount >= 0",
            name=op.f("ck_subscription_checkouts_amounts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_checkouts_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_subscription_checkouts_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_checkouts")),
    )
    op.create_index(
        "ix_subscription_checkouts_tenant_business",
        "subscription_checkouts",
        ["tenant_id", "business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_checkouts_tenant_id"),
        "subscription_checkouts",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "uq_subscription_checkouts_gateway_invoice_id",
        "subscription_checkouts",
        ["gateway_invoice_id"],
        unique=True,
        postgresql_where=sa.text("gateway_invoice_id IS NOT NULL"),
    )
    # ### end Alembic commands ###

    op.execute("ALTER TABLE subscription_checkouts ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE subscription_checkouts FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY tenant_isolation ON subscription_checkouts "
        f"USING ({_TENANT}) WITH CHECK ({_TENANT})"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON subscription_checkouts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_subscription_checkouts_gateway_invoice_id",
        table_name="subscription_checkouts",
        postgresql_where=sa.text("gateway_invoice_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_subscription_checkouts_tenant_id"), table_name="subscription_checkouts")
    op.drop_index("ix_subscription_checkouts_tenant_business", table_name="subscription_checkouts")
    op.drop_table("subscription_checkouts")
    # ### end Alembic commands ###
