"""Filesystem storage for business photos."""

import os
import re
from pathlib import Path
from typing import Protocol

#: Keys are generated by NOVA (`tenant/photo/variant.webp`, all UUIDs and a
#: fixed variant name), never taken from a request. This pattern is a second
#: line of defence: nothing outside it can name a path, so `..` or an absolute
#: path can never reach the filesystem.
_KEY = re.compile(r"^[0-9a-f-]{36}/[0-9a-f-]{36}/[a-z]+\.webp$")


class ImageStore(Protocol):
    def save(self, key: str, data: bytes) -> None: ...

    def read(self, key: str) -> bytes | None: ...

    def delete(self, key: str) -> None: ...


class LocalImageStore:
    def __init__(self, root: str | os.PathLike[str]) -> None:
        self.root = Path(root)

    def _path(self, key: str) -> Path:
        if not _KEY.match(key):
            raise ValueError(f"Not a storage key: {key!r}")
        return self.root / key

    def save(self, key: str, data: bytes) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write then rename, so a reader never sees half a file.
        tmp = path.with_suffix(".tmp")
        tmp.write_bytes(data)
        tmp.replace(path)

    def read(self, key: str) -> bytes | None:
        try:
            return self._path(key).read_bytes()
        except FileNotFoundError:
            return None

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)
