import { chromium } from '@playwright/test';
import fs from 'node:fs';
const seed = JSON.parse(fs.readFileSync('/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/seed.json','utf8'));
let t; for(;;){ const r=await fetch('http://localhost:8000/api/v1/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:seed.email,password:seed.password})}); t=await r.json(); if(r.status!==429)break; await new Promise(x=>setTimeout(x,15000)); }
const b = await chromium.launch();
const ctx = await b.newContext({viewport:{width:1366,height:900}});
await ctx.addInitScript(([t,s])=>{localStorage.setItem('nova.theme','light');localStorage.setItem('nova.auth.v1',JSON.stringify({accessToken:t.access_token,refreshToken:t.refresh_token}));localStorage.setItem('nova.activeTenantId',s.tenant);localStorage.setItem('nova.businessByTenant',JSON.stringify({[s.tenant]:s.business}));},[t,seed]);
const p = await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message)); p.on('response',r=>{ if(r.url().includes('/api/')&&r.status()>=400) errs.push(r.status()+' '+new URL(r.url()).pathname); });
await p.goto('http://localhost:5173/app/catalog',{waitUntil:'networkidle'});
await p.getByRole('tab',{name:'Photos'}).click(); await p.waitForTimeout(800);
// cover
let chooser = p.waitForEvent('filechooser'); await p.getByRole('button',{name:/Add a cover photo/}).click(); await (await chooser).setFiles('/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/photos/salon-0.jpg');
await p.waitForTimeout(2500);
chooser = p.waitForEvent('filechooser'); await p.getByRole('button',{name:'Add photos'}).click();
await (await chooser).setFiles(['/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/photos/salon-1.jpg','/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/photos/salon-2.jpg','/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/photos/salon-3.jpg','/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/photos/salon-4.jpg']);
await p.waitForTimeout(6000);
await p.screenshot({path:'/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/photoshots/dashboard.png', fullPage:true});
const slug = (await (await fetch('http://localhost:8000/api/v1/discovery/businesses?q=Lumi')).json()).items[0].slug;
await p.goto('http://localhost:5173/discover',{waitUntil:'networkidle'}); await p.waitForTimeout(800);
await p.screenshot({path:'/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/photoshots/discover.png'});
await p.goto('http://localhost:5173/discover/'+slug,{waitUntil:'networkidle'}); await p.waitForTimeout(800);
await p.screenshot({path:'/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/photoshots/storefront.png'});
await p.getByRole('button',{name:/Show all 5 photos/}).click(); await p.waitForTimeout(500);
await p.keyboard.press('ArrowRight'); await p.waitForTimeout(400);
await p.screenshot({path:'/tmp/claude-1000/-home-ringo-dev-container-Nova/e02158df-fe4f-4176-bc07-2a28405bee64/scratchpad/photoshots/lightbox.png'});
console.log('lightbox counter:', await p.getByRole('dialog').locator('p').first().innerText());
await p.keyboard.press('Escape');
console.log('errors:', errs.length ? errs : 'none');
await b.close();
