"""ai_agents · tools — the receptionist: services, providers, free times, holds,
and booking a held time the customer confirmed (ADR-0015).
"""

from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING
from uuid import UUID

from app.core.exceptions import DomainError, NotFoundError

if TYPE_CHECKING:  # pragma: no cover
    from app.modules.ai_agents.service import TenantServices

from app.modules.ai_agents.tools.base import (
    _ASK_TO_CONFIRM,
    BookedTicket,
    HeldSlot,
    Result,
    _already_holding,
    _held,
    _refuse,
    _same_instant,
    _shown,
)
from app.modules.ai_agents.tools.booking import SlotTools
from app.modules.ai_agents.tools.facts import bookable_service_ids, city_name, map_url


class ReceptionistTools(SlotTools):
    async def search_services(self, location_id: UUID | None = None) -> Result:
        """The services this business sells, with duration and price. location_id is
        optional: without it, every branch's services are listed."""

        async def work(services: "TenantServices") -> Result:
            branch_ids: list[UUID] = []
            if location_id is not None:
                try:
                    branch_ids = [(await services.catalog.get_location(location_id)).id]
                except NotFoundError:
                    # Live, a small model guessed a branch id instead of asking
                    # list_branches. The storefront's branches are the answer.
                    branch_ids = []
            if not branch_ids:
                branch_ids = [branch.id for branch in await self._branches(services)]
            offered = []
            bookable: set[UUID] = set()
            for branch_id in branch_ids:
                offered.extend(await services.catalog.list_services(branch_id))
                bookable |= await bookable_service_ids(services, branch_id)
            return {
                "services": [
                    {
                        "service_id": str(s.id),
                        "name": self._name(s),
                        "duration_minutes": s.duration_minutes,
                        "price": str(s.price),
                        "currency": s.currency,
                        # False: nobody here performs it, or they have no hours.
                        # Never offer it as a booking.
                        "bookable": s.id in bookable,
                    }
                    for s in offered
                    if s.is_active
                ][:20]
            }

        return await self._call("search_services", work)

    async def get_provider_info(self, provider_id: UUID) -> Result:
        """A provider's name and title."""

        async def work(services: "TenantServices") -> Result:
            provider = await services.catalog.get_provider(provider_id)
            title = provider.title_ar if self.deps.locale == "ar" else provider.title_en
            return {
                "provider_id": str(provider.id),
                "name": self._name(provider),
                "title": _shown(title),
            }

        return await self._call("get_provider_info", work)

    async def get_available_slots(
        self, provider_id: UUID, service_id: UUID, days_ahead: int = 7
    ) -> Result:
        """Real bookable start times, generated by the booking domain (docs/07 section 5)."""

        async def work(services: "TenantServices") -> Result:
            now = datetime.now(UTC)
            slots = await services.booking.availability(
                provider_id=provider_id,
                service_id=service_id,
                date_from=now,
                date_to=now + timedelta(days=max(1, min(days_ahead, 30))),
            )
            return {
                "available": len(slots),
                "starts_at": [slot.starts_at.isoformat() for slot in slots[:20]],
            }

        return await self._call("get_available_slots", work)

    async def hold_slot(
        self, service_id: str, starts_at: datetime, provider_id: UUID | None = None
    ) -> Result:
        """Holds a free time for the customer to confirm, once they asked to book it.

        Pass service_id and a starts_at that find_available_times returned. provider_id is
        optional: any qualified provider free then is chosen.
        """
        if self.deps.artifacts.held_slots:
            # One hold per reply. Live, a small model held a time and then kept
            # holding others instead of answering; each refusal cost a minute.
            return await self._run("hold_slot", _already_holding)
        held: list[HeldSlot] = []

        async def work(services: "TenantServices") -> Result:
            service = await self._service_ref(services, service_id)
            chosen = await self._free_provider(services, service.id, starts_at, provider_id)
            hold = await services.booking.hold_slot(
                provider_id=chosen,
                service_id=service.id,
                starts_at=starts_at,
                principal=self.deps.principal,
                customer_id=self.deps.customer_id,
            )
            # No token here. It is a bearer credential for the slot, the
            # response hands it to the client, and the model has no use for it:
            # the prompt, the logs and conversation memory are no place for it.
            details = await self._hold_details(services, hold)
            held.append(_held(hold, tenant_id=self.deps.tenant_id, label=details["label"]))
            return {
                "held": True,
                "starts_at": hold.starts_at.isoformat(),
                **{k: v for k, v in details.items() if k != "label"},
                "expires_at": hold.expires_at.isoformat(),
                "next_step": _ASK_TO_CONFIRM,
            }

        result = await self._call("hold_slot", work)
        if "error" not in result:
            # Recorded only now that the unit of work has committed.
            self.deps.artifacts.held_slots.extend(held)
        return result

    async def list_branches(self) -> Result:
        """This business's branches: where the customer can be seen. Each has its
        city and, when the owner placed it on the map, a map_url to share."""

        async def work(services: "TenantServices") -> Result:
            return {
                "branches": [
                    {
                        "location_id": str(location.id),
                        "name": self._name(location),
                        "city": city_name(location.city, self.deps.locale),
                        "map_url": map_url(location.latitude, location.longitude),
                    }
                    for location in await self._branches(services)
                ]
            }

        return await self._call("list_branches", work)

    async def find_available_times(self, service_id: str, days_ahead: int = 7) -> Result:
        """Free start times for a service across every provider who performs it.
        service_id is the service's id, or its name ("Classic Manicure")."""

        async def work(services: "TenantServices") -> Result:
            service = await self._service_ref(services, service_id)
            return await self._times_for_service(services, service.id, days_ahead)

        return await self._call("find_available_times", work)

    async def book_held_slot(self, starts_at: datetime) -> Result:
        """Books a time held for the customer in an EARLIER message, once they pressed
        "Yes, book it" on it.

        Issues their QR check-in ticket too. A time held in this same reply cannot
        be booked yet, and neither can one the customer only agreed to in words:
        the model's reading of "yes" is exactly what text in a listing or a
        message could fake, so the confirmation comes from the client's button.
        """
        offer = next((o for o in self.deps.offers if _same_instant(o.starts_at, starts_at)), None)
        if offer is None:
            held_now = any(
                _same_instant(h.starts_at, starts_at) for h in self.deps.artifacts.held_slots
            )
            self.deps.artifacts.booking_failures.append(
                ("not_confirmed_yet", "")
                if held_now
                else ("not_offered", "that time was not held for you")
            )
            return await self._run(
                "book_held_slot",
                lambda: _refuse(
                    "not_confirmed_yet" if held_now else "not_offered",
                    "STOP: do not call book_held_slot again in this reply. " + _ASK_TO_CONFIRM
                    if held_now
                    else "That time was not held for this customer. Hold it with a hold tool, "
                    "show it to them, and book it after they confirm.",
                ),
            )
        if offer.hold_token != self.deps.confirmed_hold_token:
            self.deps.artifacts.booking_failures.append(("not_confirmed", ""))
            return await self._run(
                "book_held_slot",
                lambda: _refuse(
                    "not_confirmed",
                    "STOP: nothing was booked. The customer has not confirmed this time. "
                    'Tell them to press "Yes, book it" under it.',
                ),
            )
        booked: list[BookedTicket] = []

        async def referral() -> str | None:
            # A marketplace offer attributes to the marketplace, recorded the same
            # way a storefront visit records it (ADR-0010).
            if offer.business_slug is None or self.deps.discovery is None:
                return self.deps.referral_token
            try:
                async with self.deps.discovery() as discovery:
                    issued = await discovery.record_referral(offer.business_slug)
            except DomainError:
                # An unlisted business still books; it is simply not attributed.
                return None
            return issued.token

        async def work(services: "TenantServices") -> Result:
            customer_id = self.deps.customer_id
            if customer_id is None:  # pragma: no cover - the router always resolves one
                raise NotFoundError("There is no customer to book for.")
            now = datetime.now(UTC)
            booking = await services.booking.create(
                location_id=offer.location_id,
                service_id=offer.service_id,
                provider_id=offer.provider_id,
                customer_reference_id=customer_id,
                self_service=self.deps.self_service,
                starts_at=offer.starts_at,
                referral_token=referral_token,
                # An expired hold no longer reserves the time; booking without it
                # still succeeds while the time is free, and says so when not.
                hold_token=offer.hold_token if offer.expires_at > now else None,
            )
            issued = await services.queue.issue_ticket(booking_id=booking.id)
            business = await services.catalog.get_business(booking.business_id)
            booked.append(
                BookedTicket(
                    booking_id=booking.id,
                    tenant_id=booking.tenant_id,
                    business_name=self._name(business),
                    booking_status=str(booking.status),
                    starts_at=booking.slot.starts_at,
                    ends_at=booking.slot.ends_at,
                    ticket_id=issued.ticket.id,
                    ticket_code=issued.ticket.ticket_code,
                    qr_payload=issued.qr_payload,
                    expires_at=issued.ticket.expires_at,
                    ticket_page_url=issued.ticket_page_url,
                )
            )
            # The QR payload is the customer's credential: the client gets it,
            # the model does not.
            return {
                "booked": True,
                "booking_status": str(booking.status),
                "starts_at": booking.slot.starts_at.isoformat(),
                "ticket_code": issued.ticket.ticket_code,
                "business": self._name(business),
            }

        referral_token = await referral()
        scope = self._tenant_scope(offer.tenant_id or self.deps.tenant_id)
        result = await self._call_in("book_held_slot", scope, work)
        if "error" in result:
            # Kept for the service: a model may still tell the customer it booked.
            self.deps.artifacts.booking_failures.append(
                (str(result["error"]), str(result.get("message", "")))
            )
        else:
            # Recorded only now that the unit of work has committed.
            self.deps.artifacts.tickets.extend(booked)
            self.deps.artifacts.booking_ids.extend(t.booking_id for t in booked)
            self.deps.artifacts.used_offers.add(offer.hold_token)
        return result
